### PR TITLE
Switch unmaintained ccharset to charset-normalizer

### PR DESCRIPTION
**Pull request by nanonyme**
Fixes https://github.com/hotdoc/hotdoc/issues/245

### CODE REVIEW

**Comment by nanonyme** [comment]
I am drafting this because I forgot to update requirements.txt

**Comment by thiblahute** [comment]
Makes sense to me, I do not think we care about EOL python versions in any case! (I would also agree to support only >= 3.7 like meson does fwiw).

**Comment by nanonyme** [comment]
I think this is already only tested on 3.6, 3.7 and 3.8 which are fine for charset-normalizer dependency. It's just setup.py had obsolete documentation. It's unlikely this project has supported those Python versions for a long time if it hasn't been tested with them.

**Comment by MathieuDuponchelle** [comment]
Let's go, thanks a bunch :)

**Comment by eli-schwartz** [comment]
Hmm, it looks like requirements.txt doesn't contain chardet-normalizer at all, because it was regenerated without flex installed and so the c extension was disabled.

**Comment by nanonyme** [comment]
Ugh. I will try to regenerate unless someone beats me to it.

**Comment by nanonyme** [comment]
Done at https://github.com/hotdoc/hotdoc/pull/247

**Comment by MathieuDuponchelle** [comment]
hey @nanonyme I only just noticed that documentation build times have quadrupled for the GStreamer documentation, and given the original duration was around one minute that is a significant regression :( Someone has forked `cchardet` to merge PRs that got stuck due to the maintainer going AWOL but I have issues with the fork: https://github.com/PyYoshi/cChardet/issues/81#issuecomment-1337292532 . Do you have an alternative to propose?

**Comment by nanonyme** [comment]
Sorry, no. This is the thing everyone is using.

**Comment by MathieuDuponchelle** [comment]
@nanonyme it seems unlikely that "everyone" would have settled with such a drastic performance hit (it is presumably much more than 4 times, as character set detection originally constituted a much smaller fraction of the total build time) :)

**Comment by nanonyme** [comment]
It's possible charset detection is enough of a niche these days where everyone uses UTF-8 that this kind of libraries aren't that common anymore. I can say for sure this is by far most used framework

**Comment by nanonyme** [comment]
Note if you wanted to start maintaining ccharset, the fixes to it to make it work on newer Python are not massive. The problem is it's a dead project and integrating said changes is impossible

**Comment by eli-schwartz** [comment]
You're not the first person to hit this problem. Other people simply flatly refused to touch chardet_normalizer with a ten-foot barge pole.

https://github.com/kovidgoyal/calibre/pull/1690#issuecomment-1186103137

> That's a pure python implementation. The whole point of using cchardet is that it's a lot faster than pure python implementations (calibre used to use the python chardet package). If cchardet is not being maintained, I will simply fork it and maintain it myself as I do for many other python packages.

What calibre ended up doing is adding a really small CPython extension entry point to uchardet, which is basically what cchardet is, and then include that really small wrapper inside calibre itself.

**Comment by nanonyme** [comment]
That wrapper is GPL and not good for this project, probably.

**Comment by nanonyme** [comment]
To be honest, I would suggest making the wrapper with CFFI to minimize risk that it stops being compatible with future versions of Python.

**Comment by MathieuDuponchelle** [comment]
right, thanks @eli-schwartz and yes "everyone" was a bit over-selling adoption it seems @nanonyme :P I'm not against writing a CFFI wrapper, I basically only need a single function call in this context, I'll see if I find time to work on this or if the person behind the cchardet fork can fix the issues I was having first.

Of course if you feel like writing the wrapper @nanonyme that would be welcome too :)

**Comment by nanonyme** [comment]
I already ended up reading the GPL-licensed implementation, however, maybe it doesn't really matter since CFFI wrapper might not look much like it, much of the code is boilerplate around Python C API. I don't really think it's a good idea to have yet another wrapper around Python C API anyway since that is the reason why we ended up in problems with cchardet in the first place. CFFI insulates us from Python C API changes.

**Pull request merged**
