### PR TITLE
Switch to pre-commit, for commit hook

### PR DESCRIPTION
**Pull request by ferdnyc**
pre-commit (https://pre-commit.com/) is a modular hooks manager that can be used to maintain and configure commit hooks. 

I got a bit hung up recently, after following the directions in `HACKING.md` and discovering that the existing `git-pylint-commit-hook` and `git-pep8-commit-hook` are outdated and can't be used with modern Python. So, they'll always fail your commits if you actually activate them.

This PR therefore replaces them with the Python `pre-commit` package, and the following hooks configuration (in `.pre-commit-config.yaml`):
```yaml
repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/pylint
    rev: v3.0.1
    hooks:
    -   id: pylint
        args:
          -   --fail-under=7
```

#### Hook notes

`autopep8` **will REFORMAT source files in the (attempted) commit** when run, but will not autocommit those changes. If there are any differences between the attempted commit and the reformatted commit, it will fail the check and its modifications will be left behind as unstaged changes.

So, a user can just make their changes, run `git commit`, and, if the `autopep8` check fails, simply `git add <files modified by autopep8>` and then reattempt the `git commit`.

There's no `pre-commit` hook for the `pep8` module itself, so `autopep8` is the best available option. 

#### Other changes

This PR also contains:

1. A `dev-requirements.txt` listing `pre-commit` and   `pip-tools` as dependencies, along with new instructions in `HACKING.md` to set up for development by running:
    ```bash
    pip install -r dev-requirements.txt
    pre-commit install --install-hooks
    ```

2. A commit checking in the results of running `autopep8` on all Python sources in the repo

3. Commits replacing the most egregious issues that would cause `pylint` checks to fail:
     - Use of the deprecated `cgi.escape` in `parsers/gtk_doc.py`
     - Use of `hotdoc.core.config.ConfigParser` and Python2 unparenthesized `print` in `hotdoc/extensions/gi/transition_scripts/hotdoc_gtk_doc_scan_parser`

### CODE REVIEW

**Comment by thiblahute** [comment]
I think that is a good idea.

**Comment by ferdnyc** [comment]
One thing that's always bugged me about `pep8` (and _most_ Python code formatters) is that they default to the "shoved-waaaaaaaay-over-to-the-right" hanging indentation, for function arguments.

If you move _all_ the other arguments to the next line, it'll respect that, but if you have anything after the open paren you get the "shoved-waaaaaaaay-over-to-the-right" nonsense.

IOW, if it finds this in the code:
```python3
        self.__ext.create_symbol(SignalSymbol,
            parameters=parameters,
            display_name=node.name, unique_name=unique_name,
            filename=self.__current_filename)
```

it's going to turn it into _this_:
```python3
        self.__ext.create_symbol(SignalSymbol,
                                 parameters=parameters,
                                 display_name=node.name, unique_name=unique_name,
                                 filename=self.__current_filename)
```

But if your code contains **this**, `autopep8` will leave it alone:
```python3
        self.__ext.create_symbol(
            SignalSymbol,
            parameters=parameters,
            display_name=node.name, unique_name=unique_name,
            filename=self.__current_filename)
```

So, I just pushed a commit that "re-fixes" a bunch of `dbus_extension.py` (where there was a LOT of "shoved-waaaaaaaay-over-to-the-right") to use the chopped-down-to-the-next-line style instead.

I can go through the other files it reformatted, and switch those over as well, if you're like me and can't stand how it fixes that stuff by default.

**Comment by MathieuDuponchelle** [comment]
Thanks for the much needed housekeeping @ferdnyc , I honestly don't mind the "way shoved over to the right" behavior, but I can see how it could be annoying, let's get this in as is :)

**Comment by MathieuDuponchelle** [comment]
Needs manual rebasing however, I'll merge once that's done :)

**Comment by ferdnyc** [comment]
@MathieuDuponchelle Sure, give me 5...

**Comment by ferdnyc** [comment]
@MathieuDuponchelle Good to go!

**Comment by ferdnyc** [comment]
(This is _definitely_ going to break all of the other PRs, too. I'll fix my own up once it's in.)

**Comment by MathieuDuponchelle** [comment]
thanks :)

> (This is _definitely_ going to break all of the other PRs, too. I'll fix my own up once it's in.)

re. that, fortunately none that are likely to get merged will be too difficult to fix IMHO :)

**Pull request merged**
