### PR TITLE
Allow newer toposort.

### LINKED ISSUE #117: Require a new toposort
Toposort 1.5 was released about 9 months ago. Doesn't seem to be much changed to disallow it.

### PR DESCRIPTION
**Pull request by QuLogic**
Fixes #117.

### CODE REVIEW

**Comment by QuLogic** [comment]
Hmm, is that failure due to toposort?

**Comment by MathieuDuponchelle** [comment]
Hm no, it' a known issue with the test suite in travis, still need to look at why it happens, have you run the tests locally ?

**Comment by QuLogic** [comment]
Yes, it works fine locally.

**Comment by MathieuDuponchelle** [comment]
Cool, thanks !

**Pull request merged**
