### PR TITLE
Fix segfault in search_module.c

### PR DESCRIPTION
**Pull request by mensinda**
This PR fixes a segfault in `search_module.c` and improves the logic for handling relative paths for the generated HTML files.

### CODE REVIEW

**Comment by mensinda** [comment]
The relative path issue I am trying to fix with this PR can be seen with the following setup:

```
.
├── build
│   ├── build.ninja
│   ├── meson-info
│   │   └── ..............
│   ├── meson-logs
│   │   └── meson-log.txt
│   ├── meson-private
│   │   └── ........
│   └── RefMan.md  # Generated file I want to include
├── markdown  # Non-generated MD files
│   ├── Adding-arguments.md
│   ├── Adding-new-projects-to-wrapdb.md
│   ├── .........
│   ├── Wrap-dependency-system-manual.md
│   └── Wrap-review-guidelines.md
├── meson.build
└── sitemap.txt
```

The include directories are set to `./markdown` and `./build`. All files are addressed with just the filename. Without this PR, `RefMan.md` is generated by hotdoc as `html/../build/RefMan.html`. This causes a segfault when generating the search index due to there now existing an additional `build` directory in `html/assets/js/search` which conflicts with the indexing. Additionally, the generated HTML page does not have any CSS and looks broken in the browser.

**Comment by MathieuDuponchelle** [comment]
@mensinda that second commit is obviously correct, but the first one is slightly suspect :) Can you put up a meson branch somewhere that lets me reproduce the bug? :)

**Comment by mensinda** [comment]
Here is a snapshot on what I am currently working on: https://github.com/mensinda/meson/tree/yamlDoc

To reproduce:

```bash
cd docs
../meson.py build  # Yes, there are also some fixes to meson
ninja -C build
```

You can the manually run hotdoc in the build directory for further debugging.

**Comment by MathieuDuponchelle** [comment]
tnx

**Comment by MathieuDuponchelle** [comment]
@mensinda that branch looks interesting, why don't you implement a hotdoc extension?

**Comment by mensinda** [comment]
Basically, I want a machine readable representation of our complete reference manual ((strict)YAML based). This way we can have multiple generators for the manual. Currently, I am only working on the Markdown/hotdoc backend. But in the future, we could add a LaTeX, man page, JSON (for IDE integration), etc. backend.

With that in mind, generating `*.md` files seemed like the easiest solution to implement (also since I never looked at writing hotdoc extensions).

**Comment by MathieuDuponchelle** [comment]
Fair enough, note that the point of a hotdoc extension is to let hotdoc know about actual symbols, which would improve eg search results (actual symbols would show up first when searching)

**Comment by MathieuDuponchelle** [comment]
@mensinda I think sthg like:

```
diff --git a/hotdoc/core/tree.py b/hotdoc/core/tree.py
index 082069b..3ec4580 100644
--- a/hotdoc/core/tree.py
+++ b/hotdoc/core/tree.py
@@ -24,6 +24,7 @@ Implements standalone markdown files parsing.
 import io
 import re
 import os
+import pathlib
 from urllib.parse import urlparse
 from collections import namedtuple, defaultdict, OrderedDict
 
@@ -570,8 +571,19 @@ class Tree:
                          '%s: Invalid metadata: \n%s' % (source_file,
                                                          str(exception)))
 
-        output_path = os.path.dirname(os.path.relpath(
-            source_file, next(iter(self.project.include_paths))))
+        source_path = pathlib.Path(source_file)
+
+        output_paths = []
+        for include_path in self.project.include_paths:
+            try:
+                rel_path = source_path.relative_to(pathlib.Path(include_path))
+            except ValueError:
+                continue
+            output_paths.append(rel_path.parent)
+
+        assert(output_paths)
+
+        output_path = str(min(output_paths, key = lambda path: len(path.parts)))
 
         ast = cmark.hotdoc_to_ast(contents, self, source_file)
         return Page(source_file, False, self.project.sanitized_name, extension_name,
```

is more correct, though also more verbose, works for you?

**Comment by mensinda** [comment]
Updated the PR to use `pathlib`.

Yeah, unfortunately, `relative_to` really likes to throw, otherwise, this could have been a lot shorter.

**Comment by MathieuDuponchelle** [comment]
Updated to a more intrusive, but less guessworky version of the patch, thanks again :)

**Pull request merged**
